// more-info.js

const compatibilityInfo = {
    "ISFJ-INFJ": "ISFJs and INFJs share a strong desire for harmony and deep emotional connections. The ISFJ brings reliability and a grounded perspective to the relationship, while the INFJ offers visionary insights and a focus on future possibilities. Their shared desire to help others makes for a supportive and understanding pairing.",
    "ISFJ-INTJ": "ISFJs value tradition and stability, while INTJs are more future-focused and strategic. This balance between practicality and vision can be complementary, as ISFJs help ground the INTJ's ideas, while INTJs can help ISFJs see beyond the present moment.",
    "ISFJ-ESFP": "The ISFJ and ESFP pairing is a dynamic mix of stability and spontaneity. ISFJs are dependable and like structure, whereas ESFPs live in the moment and thrive on excitement. Together, they can provide each other with balance—ISFJs offering a sense of security and ESFPs bringing a spark of adventure.",
    "INFJ-INTJ": "INFJs and INTJs both rely heavily on intuition, but use it in different ways. INFJs are focused on people and emotions, while INTJs are focused on systems and efficiency. This can make them an insightful and balanced pairing, where each partner respects the other's strengths and perspective on life.",
    "INFJ-ENFP": "INFJs and ENFPs both love exploring new ideas, but approach them differently. INFJs tend to internalize insights and think about their long-term impact, while ENFPs enjoy external exploration and spontaneous creativity. Together, they can inspire each other and share deep conversations about ideas and possibilities.",
    "INTJ-ENTJ": "INTJs and ENTJs are both ambitious and goal-driven, but they differ in their approach. INTJs are strategic visionaries, while ENTJs are natural leaders who organize people and resources. Together, they can form a powerful team where ideas are efficiently turned into reality.",
    "ESFP-ENTJ": "ESFPs bring a playful, in-the-moment attitude, while ENTJs are driven and organized. This pairing can benefit from the balance of enjoying life’s immediate pleasures while also working towards longer-term goals. The ENTJ provides structure, and the ESFP brings energy and adaptability.",
    "ENTJ-ENTP": "ENTJs and ENTPs are both energetic and love to tackle challenges. ENTJs prefer structured planning, while ENTPs thrive on exploring multiple ideas. Together, they can challenge each other intellectually, with ENTJs bringing focus and ENTPs adding creativity and spontaneity.",
    "ENTP-ENFP": "ENTPs and ENFPs are both enthusiastic and full of ideas. ENTPs tend to be more logical and enjoy debates, while ENFPs are driven by values and emotional connections. Together, they can create a lively, imaginative environment that thrives on mutual growth and exploration.",
    "ESTJ-ISTJ": "ESTJs and ISTJs both value tradition and order. ESTJs are more outgoing and take charge of organizing environments, while ISTJs prefer to work diligently behind the scenes. Their shared values help create a stable foundation, with the ESTJ driving action and the ISTJ ensuring consistency.",
    "ISTJ-INFP": "ISTJs are practical and grounded, valuing stability, while INFPs are idealistic and driven by their values. This pairing offers an interesting balance between practicality and imagination, where each partner can help the other grow by appreciating different perspectives on life.",
    "ISFP-ISTP": "ISFPs and ISTPs are both spontaneous, but while ISFPs are driven by their values and emotions, ISTPs are motivated by logic and practicality. They can complement each other well, with ISFPs bringing warmth and ISTPs providing rational problem-solving skills.",
    "ISFP-ENFJ": "ISFPs value authenticity and are deeply in tune with their feelings, while ENFJs are natural leaders who focus on helping others grow. Together, they create a nurturing environment where both partners support each other's personal growth, with the ENFJ often taking the lead.",
    "ENFJ-ESFJ": "ENFJs and ESFJs both prioritize the well-being of others, making them a caring and considerate pairing. ENFJs are more future-focused and growth-oriented, while ESFJs excel at maintaining harmony and ensuring everyone feels comfortable. Together, they create a strong, supportive social environment.",
    "ENTP-INTP": "ENTPs and INTPs both love intellectual challenges and deep analysis. ENTPs are more outgoing and enjoy debating ideas with others, while INTPs are more reserved and prefer solitary exploration of concepts. Together, they can stimulate each other’s minds and enjoy exploring ideas from multiple angles.",
    "ENFJ-INTJ": "ENFJs use their empathy to inspire and lead others, while INTJs focus on long-term strategy and achieving goals. Together, the ENFJ brings warmth and understanding to balance the INTJ’s logical approach, creating a partnership that is both emotionally supportive and goal-driven.",
    "ISFJ-ESTJ": "ISFJs and ESTJs both value tradition, reliability, and hard work. The ISFJ is nurturing and supportive, while the ESTJ is a natural leader who takes charge. Together, they can create a stable environment, with each respecting the other's contributions to maintaining structure and order.",
    "ISTP-ESTP": "ISTPs and ESTPs both thrive on hands-on experiences and spontaneity. ISTPs are more analytical and enjoy understanding how things work, while ESTPs are social and quick to take action. Together, they form a dynamic duo that is always ready for an adventure or a challenge.",
    "ESTJ-ENFJ": "ESTJs are focused on efficiency and organization, while ENFJs prioritize the emotional growth and well-being of others. Together, they can balance each other's strengths—ESTJs bring structure, and ENFJs bring empathy, creating an environment where both practical and emotional needs are met.",
    "INFP-INFJ": "INFPs and INFJs are both idealistic and seek deeper meaning in life. INFPs are guided by their inner values, while INFJs look for insights to help others. Together, they can inspire one another, with the INFJ offering a vision for the future and the INFP staying true to their values.",
    "ISFP-ENTP": "ISFPs are deeply connected to their values and prefer to live in the moment, while ENTPs thrive on debate and exploring ideas. ISFPs bring warmth and authenticity, whereas ENTPs offer creativity and logical analysis, making for an intriguing and dynamic relationship.",
    "ISTJ-ENFP": "ISTJs value structure and predictability, while ENFPs are spontaneous and creative. This pairing can offer balance, as ISTJs provide a solid foundation and ENFPs bring new ideas and enthusiasm, helping each other grow in areas they may not naturally prioritize."
  };
  
  export default compatibilityInfo;